export const SITE = {
  name: 'Chill Bali Trips',
  tagline: "Bali's #1 Concierge Service",
  description: 'Premium Bali concierge service offering private tours, adventure activities, and personalized itineraries. Book your dream Bali experience with local expert Gede.',
  url: 'https://chillbalitrips.com',
  whatsapp: '+6287750128880',
  whatsappDisplay: '+62 877-5012-8880',
  whatsappMessage: "Hi! I found you on Chill Bali Trips and I'm planning a trip to Bali. Would love your help with...",
  instagram: 'https://www.instagram.com/balitravelcompanion',
  instagramHandle: '@balitravelcompanion',
  facebook: 'https://www.facebook.com/share/14RkUqhXQKT/?mibextid=wwXIfr',
  email: 'hello@chillbalitrips.com',
  operator: 'Gede',
};

export const ACTIVITIES = [
  {
    slug: 'atv-quad-biking',
    title: 'ATV & Quad Biking',
    shortTitle: 'ATV Riding',
    description: 'Race through rice terraces, jungle trails, and river crossings on powerful ATVs. Choose from beginner-friendly paths to advanced off-road adventures.',
    price: 'From $35/person',
    duration: '2-3 hours',
    difficulty: 'Easy to Moderate',
    location: 'Ubud / Tabanan',
    image: 'https://images.unsplash.com/photo-1534293506745-bdd75da882ce?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Rice terrace trails', 'Jungle river crossings', 'Volcano views', 'Professional guides'],
  },
  {
    slug: 'bali-swing',
    title: 'Bali Swing Experience',
    shortTitle: 'Bali Swing',
    description: 'Soar above the jungle canopy on Bali\'s iconic swings. Multiple swing heights, photo spots, and stunning valley views included.',
    price: 'From $25/person',
    duration: '2-4 hours',
    difficulty: 'Easy',
    location: 'Ubud',
    image: 'https://images.unsplash.com/photo-1576475706812-822620fc23ba?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Multiple swing heights', 'Nest photo spots', 'Jungle valley views', 'Instagram-worthy'],
  },
  {
    slug: 'white-water-rafting',
    title: 'White Water Rafting',
    shortTitle: 'Rafting',
    description: 'Paddle through Class II-III rapids on the Ayung or Telaga Waja rivers. Stunning gorge scenery, waterfalls, and a rush of adrenaline.',
    price: 'From $30/person',
    duration: '3-4 hours',
    difficulty: 'Moderate',
    location: 'Ubud / Karangasem',
    image: 'https://images.unsplash.com/photo-1504656738986-9387b6a8acc9?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Class II-III rapids', 'Gorge scenery', 'Waterfall views', 'Lunch included'],
  },
  {
    slug: 'mount-batur-sunrise-trek',
    title: 'Mount Batur Sunrise Trek',
    shortTitle: 'Sunrise Trek',
    description: 'Hike an active volcano in the dark and watch the sun rise over the caldera lake. One of Bali\'s most unforgettable experiences.',
    price: 'From $45/person',
    duration: '6-8 hours',
    difficulty: 'Moderate to Hard',
    location: 'Kintamani',
    image: 'https://images.unsplash.com/photo-1604314435281-8ce274f1597c?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Active volcano', 'Sunrise panorama', 'Caldera lake views', 'Breakfast at summit'],
  },
  {
    slug: 'waterfall-tours',
    title: 'Waterfall Tours',
    shortTitle: 'Waterfalls',
    description: 'Discover Bali\'s most stunning waterfalls — from the iconic Tegenungan to hidden gems like Tukad Cepung and Sekumpul.',
    price: 'From $40/person',
    duration: '4-8 hours',
    difficulty: 'Easy to Moderate',
    location: 'Various',
    image: 'https://plus.unsplash.com/premium_photo-1697730247123-0ce641e72388?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Multiple waterfalls', 'Hidden gems', 'Swimming spots', 'Photo opportunities'],
  },
  {
    slug: 'dolphin-watching',
    title: 'Dolphin Watching',
    shortTitle: 'Dolphins',
    description: 'Early morning boat trip to spot wild dolphins in their natural habitat off the coast of Lovina, North Bali.',
    price: 'From $15/person',
    duration: '2-3 hours',
    difficulty: 'Easy',
    location: 'Lovina',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Wild dolphins', 'Sunrise views', 'Traditional boat', 'North Bali coast'],
  },
  {
    slug: 'coffee-plantation-tour',
    title: 'Coffee Plantation Tour',
    shortTitle: 'Coffee Tour',
    description: 'Visit traditional Balinese coffee plantations. Learn about Luwak coffee production, taste exotic blends, and enjoy volcano views.',
    price: 'From $20/person',
    duration: '2-3 hours',
    difficulty: 'Easy',
    location: 'Ubud / Kintamani',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Luwak coffee tasting', 'Plantation walk', 'Exotic blends', 'Volcano backdrop'],
  },
  {
    slug: 'temple-tours',
    title: 'Temple Tours',
    shortTitle: 'Temples',
    description: 'Explore Bali\'s most sacred and beautiful temples — from the cliff-top Uluwatu to the water temple Tirta Empul.',
    price: 'From $40/person',
    duration: '4-8 hours',
    difficulty: 'Easy',
    location: 'Various',
    image: 'https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Uluwatu sunset', 'Tirta Empul purification', 'Tanah Lot', 'Besakih Mother Temple'],
  },
  {
    slug: 'snorkeling-diving',
    title: 'Snorkeling & Diving',
    shortTitle: 'Snorkeling',
    description: 'Discover vibrant coral reefs, manta rays, and the famous USAT Liberty shipwreck. Spots for beginners and certified divers.',
    price: 'From $35/person',
    duration: '4-8 hours',
    difficulty: 'Easy to Moderate',
    location: 'Nusa Penida / Amed / Tulamben',
    image: 'https://images.unsplash.com/photo-1566987827971-f2c40e748a54?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Manta rays', 'Coral reefs', 'Shipwreck dive', 'Crystal clear water'],
  },
  {
    slug: 'cycling-tours',
    title: 'Cycling Tours',
    shortTitle: 'Cycling',
    description: 'Ride through terraced rice paddies, traditional villages, and stunning countryside on guided cycling adventures.',
    price: 'From $30/person',
    duration: '3-5 hours',
    difficulty: 'Easy to Moderate',
    location: 'Ubud / Kintamani',
    image: 'https://images.unsplash.com/photo-1624352639222-99c4461975ec?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Downhill routes', 'Village visits', 'Rice terraces', 'Local snacks'],
  },
  {
    slug: 'surfing-lessons',
    title: 'Surfing Lessons',
    shortTitle: 'Surfing',
    description: 'Learn to surf on Bali\'s beginner-friendly beaches or challenge yourself at world-class breaks like Uluwatu and Padang Padang.',
    price: 'From $25/person',
    duration: '2-3 hours',
    difficulty: 'All levels',
    location: 'Seminyak / Canggu / Uluwatu',
    image: 'https://images.unsplash.com/photo-1654137065487-cce388f2c58f?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['All skill levels', 'Board rental', 'Certified instructors', 'Warm tropical water'],
  },
  {
    slug: 'spa-wellness',
    title: 'Spa & Wellness',
    shortTitle: 'Spa',
    description: 'Indulge in world-class Balinese spa treatments, yoga sessions, wellness retreats, and holistic healing experiences.',
    price: 'From $20/person',
    duration: '1-4 hours',
    difficulty: 'Easy',
    location: 'Various',
    image: 'https://images.unsplash.com/flagged/photo-1564767609342-620cb19b2357?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Balinese massage', 'Flower baths', 'Yoga sessions', 'Wellness retreats'],
  },
  {
    slug: 'cooking-classes',
    title: 'Cooking Classes',
    shortTitle: 'Cooking',
    description: 'Learn authentic Balinese cuisine from local chefs. Visit a morning market, prepare traditional dishes, and feast on your creations.',
    price: 'From $25/person',
    duration: '4-5 hours',
    difficulty: 'Easy',
    location: 'Ubud / Seminyak',
    image: 'https://images.unsplash.com/photo-1616669944447-d65b41a222bd?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Market visit', 'Hands-on cooking', '5+ dishes', 'Recipe cards'],
  },
  {
    slug: 'paintball',
    title: 'Paintball',
    shortTitle: 'Paintball',
    description: 'Battle it out at Bali\'s paintball arenas with professional equipment, multiple game scenarios, and jungle-themed courses.',
    price: 'From $25/person',
    duration: '2-3 hours',
    difficulty: 'Moderate',
    location: 'Kuta / Ubud',
    image: 'https://images.unsplash.com/photo-1650995696988-c269f4016475?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Professional gear', 'Multiple scenarios', 'Group packages', 'Jungle course'],
  },
  {
    slug: 'fishing-charters',
    title: 'Fishing Charters',
    shortTitle: 'Fishing',
    description: 'Deep sea fishing expeditions off South Bali. Target mahi-mahi, tuna, and marlin on fully-equipped charter boats.',
    price: 'From $80/person',
    duration: '4-8 hours',
    difficulty: 'Easy',
    location: 'Sanur / Jimbaran',
    image: 'https://images.unsplash.com/photo-1726250947679-3d89963934d8?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Deep sea fishing', 'Full equipment', 'Experienced crew', 'Catch and cook option'],
  },
  {
    slug: 'nusa-penida-day-trip',
    title: 'Nusa Penida Day Trip',
    shortTitle: 'Nusa Penida',
    description: 'Visit the dramatic cliffs, pristine beaches, and crystal-clear waters of Nusa Penida island — Bali\'s most photogenic neighbor.',
    price: 'From $55/person',
    duration: 'Full day',
    difficulty: 'Moderate',
    location: 'Nusa Penida',
    image: 'https://images.unsplash.com/photo-1566987827971-f2c40e748a54?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Kelingking Beach', 'Angel\'s Billabong', 'Crystal Bay', 'Broken Beach'],
  },
  {
    slug: 'private-driver',
    title: 'Private Driver & Custom Tours',
    shortTitle: 'Private Driver',
    description: 'Explore Bali at your own pace with a dedicated private driver. Fully customizable itineraries, comfortable vehicles, and local insights.',
    price: 'From $40/day',
    duration: '8-12 hours',
    difficulty: 'Easy',
    location: 'Island-wide',
    image: 'https://images.unsplash.com/photo-1755134840127-bdeb3150ede7?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Custom itinerary', 'Air-conditioned vehicle', 'English-speaking', 'Flexible schedule'],
  },
];

export const AREAS = [
  {
    slug: 'seminyak',
    title: 'Seminyak',
    description: 'Bali\'s upscale beach district — luxury resorts, world-class dining, vibrant nightlife, and stylish beach clubs.',
    vibe: 'Luxury & Nightlife',
    image: 'https://images.unsplash.com/photo-1720728659932-0233fb9b6616?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Beach clubs', 'Fine dining', 'Designer boutiques', 'Sunset bars'],
  },
  {
    slug: 'ubud',
    title: 'Ubud',
    description: 'The cultural heart of Bali — rice terraces, ancient temples, art galleries, yoga retreats, and the monkey forest.',
    vibe: 'Culture & Nature',
    image: 'https://images.unsplash.com/photo-1557093793-d149a38a1be8?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Rice terraces', 'Monkey Forest', 'Art galleries', 'Yoga & wellness'],
  },
  {
    slug: 'canggu',
    title: 'Canggu',
    description: 'Bali\'s booming digital nomad hub — surf breaks, hip cafes, coworking spaces, and a laid-back creative scene.',
    vibe: 'Surf & Digital Nomad',
    image: 'https://images.unsplash.com/photo-1654137065504-0e5d25238fa5?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Surf breaks', 'Hip cafes', 'Coworking', 'Rice field walks'],
  },
  {
    slug: 'uluwatu',
    title: 'Uluwatu',
    description: 'Dramatic clifftop temples, world-class surf, hidden beaches, and Bali\'s most stunning sunset views.',
    vibe: 'Cliffs & Surf',
    image: 'https://images.unsplash.com/photo-1523810804307-760585ed63cd?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Cliff temples', 'Secret beaches', 'World-class surf', 'Kecak fire dance'],
  },
  {
    slug: 'pererenan',
    title: 'Pererenan',
    description: 'Bali\'s hidden gem — peaceful rice fields, uncrowded beaches, authentic village life, and a growing cafe scene.',
    vibe: 'Hidden Gem',
    image: 'https://images.unsplash.com/photo-1589443152682-5b24e1abd34f?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Quiet beaches', 'Rice paddies', 'Local villages', 'Authentic Bali'],
  },
  {
    slug: 'lovina',
    title: 'Lovina',
    description: 'North Bali\'s tranquil coast — dolphin watching, volcanic hot springs, waterfalls, and a peaceful escape from the south.',
    vibe: 'Peaceful & Natural',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800&h=600&fit=crop&auto=format&q=80',
    highlights: ['Dolphin watching', 'Hot springs', 'Waterfalls', 'Black sand beaches'],
  },
];

export const TESTIMONIALS = [
  {
    name: 'Sarah & James',
    location: 'Melbourne, Australia',
    text: 'Gede made our honeymoon absolutely magical. Every detail was perfect — from the sunrise trek to the private dinner on the beach. We didn\'t have to worry about a single thing.',
    rating: 5,
  },
  {
    name: 'Mike',
    location: 'London, UK',
    text: 'Best decision we made was hiring Gede as our guide. His local knowledge is incredible — he took us to hidden waterfalls and restaurants that no tourist would ever find.',
    rating: 5,
  },
  {
    name: 'Emily & Tom',
    location: 'Los Angeles, USA',
    text: 'We came to Bali with zero plan and Gede built us a perfect 10-day itinerary in hours. Fair prices, amazing experiences, and he was available on WhatsApp 24/7.',
    rating: 5,
  },
  {
    name: 'Lisa',
    location: 'Toronto, Canada',
    text: 'As a solo female traveler, I felt completely safe with Gede. He\'s professional, knows everyone, and genuinely cares about making your trip special.',
    rating: 5,
  },
  {
    name: 'David & Emma',
    location: 'Sydney, Australia',
    text: 'Third time using Chill Bali Trips and we wouldn\'t trust anyone else. Gede is the best in the business — responsive, reliable, and always goes above and beyond.',
    rating: 5,
  },
];

export function getWhatsAppLink(message?: string) {
  const msg = message || SITE.whatsappMessage;
  return `https://wa.me/${SITE.whatsapp}?text=${encodeURIComponent(msg)}`;
}
